/* Pentagon numbers */
/* Problem 44 */

/* Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are: */

/* 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ... */

/* It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal. */

/* Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk − Pj| is minimised; what is the value of D? */

#include <stdio.h>

int find_num (int *array, int key, int length) {
	int lo = 0, hi = length - 1;
	int mid;

	while (lo <= hi) {
		mid = (lo + hi) / 2;
		if (key > array[mid])
			lo = mid + 1;
		else if (key < array[mid])
			hi = mid - 1;
		else return mid;
	}
	return 0;
}

int main (int argc, char **argv) {
	int D, i, j, limit = atoi(argv[1]);
	int pentagonal[limit];

	for (i = 1; i <= limit; i++)
		pentagonal[i-1] = (i * (3 * i - 1)) >> 1;

	for (i = 0; i < limit; i++)
		for (j = i+1; j < limit; j++)
			if (find_num (pentagonal, D = pentagonal[j] - pentagonal[i], limit))
				if (find_num (pentagonal, pentagonal[j] + pentagonal[i], limit))
					goto end;

end: return printf ("%d - %d = %d\n", pentagonal[j], pentagonal[i], D);
}
